name: 🔗 GHA
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to use for the build'
        type: string
        default: 'godotengine/godot'
      base-branch:
        description: 'Base branch to use for the builds'
        type: string
        default: '4.5'
      tag:
        description: 'tag to use for downloading the repo'
        type: string
        default: '4.5-stable'
      tag_release:
        description: 'tag to use for releasing the build'
        type: string
        default: '4.5-stable'
      module_flags:
        description: 'Extra module flags, e.g. module_webm_enabled=no'
        type: string
        default: ''
      template_module_flags:
        description: 'Extra module flags for template build, e.g. disable_3d=yes'
        type: string
        default: ''
      release_repo:
        description: 'Repository to use for the release (leave empty for current repo)'
        type: string
        default: ''
      lto:
        description: 'LTO mode. Options: "none", "thin", "full"'
        type: choice
        default: "lto=thin"
        options:
          - "lto=none"
          - "lto=thin"
          - "lto=full"

jobs:
  
  windows-build:
    name: 🏁 Windows
    uses: ./.github/workflows/windows_builds.yml
    with:
      repo: ${{ inputs.repo }}
      base-branch: ${{ inputs.base-branch }}
      tag: ${{ inputs.tag }}
      lto: ${{ inputs.lto == 'lto=thin' && 'lto=none' || inputs.lto }}
      module_flags: ${{ inputs.module_flags }}
      template_module_flags: ${{ inputs.template_module_flags }}
    secrets: inherit

  web-build:
    name: 🌐 Web
    uses: ./.github/workflows/web_builds.yml
    with:
      repo: ${{ inputs.repo }}
      base-branch: ${{ inputs.base-branch }}
      tag: ${{ inputs.tag }}
      lto: ${{ inputs.lto }}
      module_flags: ${{ inputs.module_flags }}
      template_module_flags: ${{ inputs.template_module_flags }}
    secrets: inherit

  release:
    name: 🚀 Create Release
    permissions:
      contents: write
      actions: read
      packages: write
    needs:
      - windows-build
      - web-build
    uses: ./.github/workflows/release.yml
    with:
      base-branch: ${{ inputs.base-branch }}
      repo: ${{ inputs.repo }}
      tag: ${{ inputs.tag }}
      tag_release: ${{ inputs.tag_release }}
      lto: ${{ inputs.lto }}
      module_flags: ${{ inputs.module_flags }}
      template_module_flags: ${{ inputs.template_module_flags }}
      release_repo: ${{ inputs.release_repo }}
    secrets: inherit
